'use strict';

const restrictedGlobals = require('eslint-restricted-globals');

module.exports = {
    rules: {
        'await-promise': false,
        'ban-comma-operator': true,
        'ban': false,
        'curly': true,
        'forin': true,
        'function-constructor': true,
        'import-blacklist': false,
        'label-position': true,
        'no-arg': true,
        'no-bitwise': true,
        'no-conditional-assignment': true,
        'no-console': true,
        'no-construct': true,
        'no-debugger': true,
        'no-duplicate-super': true,
        'no-duplicate-switch-case': true,
        'no-duplicate-variable': [true,
            'check-parameters',
        ],
        'no-dynamic-delete': false,
        'no-empty': [true, 'allow-empty-catch', 'allow-empty-functions'],
        'no-eval': true,
        'no-floating-promises': false,
        'no-for-in-array': false,
        'no-implicit-dependencies': true,
        'no-inferred-empty-object-type': false,
        'no-invalid-template-strings': true,
        'no-invalid-this': false,
        'no-misused-new': true,
        'no-null-keyword': false,
        'no-object-literal-type-assertion': [true, { 'allow-arguments': true }],
        'no-restricted-globals': [true].concat(restrictedGlobals),
        'no-return-await': true,
        'no-shadowed-variable': true,
        'no-sparse-arrays': true,
        'no-string-literal': true,
        'no-string-throw': true,
        'no-submodule-imports': true,
        'no-switch-case-fall-through': true,
        'no-tautology-expression': true,
        'no-this-assignment': true,
        'no-unbound-method': false,
        'no-unnecessary-class': false,
        'no-unsafe-any': false,
        'no-unsafe-finally': true,
        'no-unused-expression': true,
        'no-use-before-declare': false, // disable this rule as it is very heavy performance-wise and not that useful
        'no-var-keyword': true,
        'no-void-expression': false,
        'prefer-conditional-expression': true,
        'prefer-object-spread': true,
        'radix': false,
        'restrict-plus-operands': false,
        'static-this': true,
        'strict-boolean-expressions': false,
        'strict-type-predicates': false,
        'switch-default': true,
        'triple-equals': [true, 'allow-null-check'],
        'unnecessary-constructor': true,
        'use-default-type-parameter': false,
        'use-isnan': true,
    },
};
