'use strict';

module.exports = {
    rules: {
        'array-type': [true, 'array-simple'],
        'arrow-return-shorthand': true,
        'binary-expression-operand-order': true,
        'callable-types': true,
        'class-name': true,
        'comment-format': [true, 'check-space'],
        'comment-type': [true, 'doc', 'singleline', 'directive'],
        'completed-docs': false,
        'encoding': true,
        'file-header': false,
        'file-name-casing': false,
        'increment-decrement': false,
        'interface-name': false,
        'interface-over-type-literal': true,
        'match-default-export-name': false,
        'newline-per-chained-call': false,
        'no-angle-bracket-type-assertion': true,
        'no-boolean-literal-compare': false,
        'no-parameter-properties': false,
        'no-redundant-jsdoc': false,
        'no-reference-import': true,
        'no-unnecessary-callback-wrapper': true,
        'no-unnecessary-initializer': true,
        'no-unnecessary-qualifier': false,
        'object-literal-key-quotes': [true, 'consistent-as-needed'],
        'object-literal-shorthand': true,
        'one-line': [true,
            'check-catch',
            'check-finally',
            'check-else',
            'check-open-brace',
            'check-whitespace',
        ],
        'one-variable-per-declaration': true,
        'ordered-imports': [true, {
            'import-sources-order': 'lowercase-last',
            'grouped-imports': true,
            'module-source-path': 'full',
            'named-imports-order': 'lowercase-last',
        }],
        'prefer-function-over-method': true,
        'prefer-method-signature': true,
        'prefer-switch': false,
        'prefer-template': [true, 'allow-single-concat'],
        'prefer-while': true,
        'return-undefined': true,
        'space-before-function-paren': [true, {
            anonymous: 'always',
            named: 'never',
            asyncArrow: 'always',
            constructor: 'never',
            method: 'never',
        }],
        'space-within-parens': [true, 0],
        'switch-final-break': [true, 'never'],
        'type-literal-delimiter': true,
        'unnecessary-bind': true,
        'unnecessary-else': true,
        'variable-name': [true,
            'check-format',
            'require-const-for-all-caps',
            'allow-pascal-case',
            'ban-keywords',
        ],
    },
};
